# Site
repository: KChalk/kchalk.github.io
# favicon: images/favicon.ico

# Personal info
name: Kendra Chalkley
title: Computational Linguist
email: kd.chalkley@gmail.com
website: www.github.com/KChalk/kchalk.github.io

#title: KChalk
author: Kendra Chalkley
description: > 
  Personal website of Kendra Chalkley

# Social links
twitter_username: KDChalkley
github_username: kchalk
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: kchalk
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Kendra, a compuational linguist, data scientist, machine learning engineer, reasearcher, etc. I've just finished my second degree and I'm looking for my first job in tech!

  I am most skilled in: <mark>natural language processing</mark>, <mark>deep learning</mark>, and <mark> data visualization</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Board Games
   - Tango/blues/fusion dancing
   - Dogs
   - Befriending nerds :)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
#theme: jekyll-theme-slate

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

google_analytics: UA-141697754-1
