title: kchalk
author: Kendra Chalkley
email: kd.chalkley@gmail.com
description: > 
  Personal website of Kendra Chalkley

twitter_username: KDChalkley
github_username: kchalk

show_downloads: false
theme: jekyll-theme-slate
featured-img: profile.jpg
google_analytics: UA-141697754-1
