# site settings
title: Kendra Chalkley
subtitle: A portfolio etc
email: k@kchalk.com
description: Portfolio and resume of Kendra Chalkley, computational linguist, machine learning engineer, data scientist, and recent gradaute. I'm looking for work; Hire me!  
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kendra Chalkley
#street_address: 1234 Somewhere Road 
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kchalk
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/kchalk
#pinterest_url:
#slack_url:
twitter_url: https://twitter.com/kdchalkley

# build settings
markdown: kramdown

sass:
  style: compressed
