title: kchalk on Github
author: Kendra Chalkley
email: kd.chalkley@gmail.com
description: > 
  Personal website of Kendra Chalkley

twitter_username: KDChalkley
github_username: kchalk

theme: jekyll-theme-slate
google_analytics: UA-141697754-1
